


for i=2:2
    fileID = fopen(['myqsub' num2str(i) '.sh'],'w');
    command = [...
    '#!/bin/sh -l \n' ...
    '# FILENAME:  myqsub' num2str(i) '.sh\n'...
    '#PBS -q standby\n'...
    '#PBS -l nodes=1:ppn=1 \n'...
    '#PBS -l walltime=4:00:00\n\n'...
    '# Change to the directory \n' ...
    'cd $PBS_O_WORKDIR\n'...
    'cd .. \n'...
    './FiberMpp ' num2str(i) '\n'...
    ];

    fprintf(fileID,command);
    fclose(fileID);
    
    
    system(['qsub myqsub' num2str(i) '.sh']);
end
